import { createAction } from 'redux-actions';

export default {
    'RECIPE/FETCH_RECIPES_SUCCESSFULLY': createAction("RECIPE/FETCH_RECIPES_SUCCESSFULLY"),
    'RECIPE/RECIPE_FETCH_RECIPES_ERROR': createAction("RECIPES/RECIPE_FETCH_RECIPES_ERROR"),
    'RECIPE/RECIPES_REMOVE_ALL': createAction("RECIPE/RECIPES_REMOVE_ALL"),

}